name: Bug Report 🐛

description: Report a bug.

title: "bug: <title>"

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Provide contact details if follow-up is needed.
      placeholder: e.g. discord@username
    validations:
      required: false

  - type: textarea
    id: reprod
    attributes:
      label: Reproduction Steps
      description: List the steps to reproduce the issue.
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the expected outcome.
      placeholder: e.g. The item should appear in the inventory.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe the actual outcome.
      placeholder: e.g. The item did not appear in the inventory.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs.
      render: shell
