name: Build

env:
  TML_BUILD_PATH_OVERRIDE: ./bin

on:
  push:
    branches: [stable]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download tModLoader
        run: |
          curl -s -L https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip -o tModLoader.zip

      - name: Extract tModLoader
        run: |
          unzip -q -o tModLoader.zip -d ../tModLoader
          rm tModLoader.zip

      - name: Create tModLoader.targets file
        shell: bash
        run: |
          cat >> ../tModLoader.targets << EOF
          <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="tModLoader\tMLMod.targets" />
          </Project>
          EOF

      - name: Build solution
        run: dotnet build Morningstar.sln --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./bin/tModLoader/Mods/Morningstar.tmod
            ./src/EndlessEscapade/bin/Release/net8.0/Morningstar.dll

  publish:
    runs-on: windows-latest

    needs: build

    steps:
      - name: Deploy action across private Discord
        uses: sarisia/actions-status-discord@v1  
        with:
          webhook: ${{ secrets.PRIVATE_DISCORD_BUILD_WEBHOOK_TOKEN }}
          title: New version of `Morningstar` is ready!
          description: |
            Click [here](https://github.com/shnakamura/Morningstar/releases/tag/test-${{ steps.date.outputs.date }}) to view.

      - name: Deploy action across public Discord
        uses: sarisia/actions-status-discord@v1  
        with:
          webhook: ${{ secrets.PUBLIC_DISCORD_BUILD_WEBHOOK_TOKEN }}
          title: New version of `Morningstar` is ready!
          description: |
            Click [here](https://github.com/shnakamura/Morningstar/releases/tag/test-${{ steps.date.outputs.date }}) to view.
